# Generated by Django 5.2 on 2025-04-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='display_top',
            field=models.CharField(choices=[('Display', 'Display'), ('None', 'None')], default='Display', max_length=7),
        ),
    ]
