# Generated by Django 5.2 on 2025-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_bofile_f_nm_summernoteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernoteimage',
            name='key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summernoteimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
