# Generated by Django 5.2 on 2025-05-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_summernoteimage_key_alter_summernoteimage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernoteimage',
            name='is_used',
        ),
    ]
