# Generated by Django 5.2 on 2025-05-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_summernoteimage_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernoteimage',
            name='bo_nm',
        ),
    ]
