# Generated by Django 5.2 on 2025-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_summernoteimage_bo_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernoteimage',
            name='bo_nm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
