# Generated by Django 5.2 on 2025-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_summernoteimage_bo_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bofile',
            name='origin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
