# Generated by Django 5.2 on 2025-05-14 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_bofile_origin_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealEvent',
            new_name='Circle',
        ),
    ]
