# Generated by Django 5.2 on 2025-05-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_rename_realevent_circle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bofile',
            old_name='f_nm',
            new_name='f_path',
        ),
        migrations.RenameField(
            model_name='summernoteimage',
            old_name='file',
            new_name='f_path',
        ),
    ]
