# Generated by Django 5.2 on 2025-05-19 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_rename_f_nm_bofile_f_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Free',
            new_name='Build',
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_seq', models.IntegerField(blank=True, default=0)),
                ('bo_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('bo_group', models.IntegerField(blank=True, default=0)),
                ('bo_co_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('bo_hit', models.IntegerField(blank=True, default='0')),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_seq', models.IntegerField(blank=True, default=0)),
                ('bo_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('bo_group', models.IntegerField(blank=True, default=0)),
                ('bo_co_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('bo_hit', models.IntegerField(blank=True, default='0')),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_seq', models.IntegerField(blank=True, default=0)),
                ('bo_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('bo_group', models.IntegerField(blank=True, default=0)),
                ('bo_co_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('bo_hit', models.IntegerField(blank=True, default='0')),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_seq', models.IntegerField(blank=True, default=0)),
                ('bo_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('bo_group', models.IntegerField(blank=True, default=0)),
                ('bo_co_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('bo_hit', models.IntegerField(blank=True, default='0')),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_seq', models.IntegerField(blank=True, default=0)),
                ('bo_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('bo_group', models.IntegerField(blank=True, default=0)),
                ('bo_co_seq_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('bo_hit', models.IntegerField(blank=True, default='0')),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
