# Generated by Django 5.2 on 2025-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_rename_free_build_general_other_photo_story_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='circle',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='other',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='pid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
